/** Descripción OpenAPI mínima (los detalles completos están en docs/API.md). */
export const openapi = {
  openapi: '3.0.3',
  info: { title: 'ReservaFlow API', version: '1.0.0', description: 'API REST del sistema de reservas ReservaFlow' },
  servers: [{ url: '/api/v1' }],
  paths: {
    '/health': { get: { summary: 'Healthcheck' } },
    '/auth/register': { post: { summary: 'Registrar cliente' } },
    '/auth/login': { post: { summary: 'Iniciar sesión' } },
    '/auth/refresh': { post: { summary: 'Renovar tokens' } },
    '/auth/me': { get: { summary: 'Perfil actual' }, patch: { summary: 'Actualizar perfil' } },
    '/categories': { get: { summary: 'Listar categorías' }, post: { summary: 'Crear categoría (admin)' } },
    '/services': { get: { summary: 'Listar servicios' }, post: { summary: 'Crear servicio (admin)' } },
    '/services/{id}': { get: { summary: 'Detalle' }, patch: { summary: 'Editar (admin)' }, delete: { summary: 'Eliminar (admin)' } },
    '/staff': { get: { summary: 'Listar profesionales (?serviceId&availableOn)' }, post: { summary: 'Crear (admin)' } },
    '/staff/{id}/availability': { get: { summary: 'Franjas de un día (?serviceId&date)' } },
    '/staff/{id}/availability/month': { get: { summary: 'Resumen mensual (?serviceId&month)' } },
    '/staff/{id}/working-hours': { get: { summary: 'Horario semanal' }, put: { summary: 'Reemplazar horario' } },
    '/staff/{id}/time-off': { get: { summary: 'Bloqueos' }, post: { summary: 'Añadir bloqueo' } },
    '/bookings/quote': { post: { summary: 'Cotizar precio con cupón/frecuencia' } },
    '/bookings': { get: { summary: 'Mis reservas / todas (según rol)' }, post: { summary: 'Crear reserva (o serie recurrente)' } },
    '/bookings/{id}': { get: { summary: 'Detalle' } },
    '/bookings/{id}/cancel': { post: { summary: 'Cancelar (opcional serie completa)' } },
    '/bookings/{id}/reschedule': { post: { summary: 'Reprogramar' } },
    '/bookings/{id}/status': { post: { summary: 'Cambiar estado (staff/admin)' } },
    '/bookings/code/{code}': { get: { summary: 'Consultar por código de confirmación' } },
    '/reviews': { get: { summary: 'Listar reseñas' }, post: { summary: 'Crear reseña' } },
    '/coupons/validate': { post: { summary: 'Validar cupón' } },
    '/coupons': { get: { summary: 'Listar (admin)' }, post: { summary: 'Crear (admin)' } },
    '/notifications': { get: { summary: 'Mis notificaciones' } },
    '/notifications/read': { post: { summary: 'Marcar leídas' } },
    '/waitlist': { get: { summary: 'Mi lista de espera' }, post: { summary: 'Unirse' } },
    '/admin/stats': { get: { summary: 'Métricas del negocio' } },
  },
} as const;
